### ISSUE TITLE
can the Pardiso dependence be removed

### ISSUE THREAD

**Issue by maxchendt** [oxfordcontrol/Clarabel.jl#108]
This is an excellent package, for my applications, it is 1000 times faster than COSMO. 

because of the `Pardiso`, it takes up more than 1G hard-disk.  `Pardiso` dependence takes too much time on installation, and the pre-compile  takes 900 seconds during `Pkg> add`.  Sometimes it is fast (I remove the `~.julia`  for each testing)

Is it the  `Pardiso` a must for `Clarabel`? Is it possible to move it to be optional?

**Comment by goulart-paul** [comment]
No, it is not a requirement and is only used if you specify ":mkl" as the direct linear solver type.

It seems that the right long term solution to fix this is to use the new conditional dependencies / extensions functionality in Pkg.jl.   It looks like that will not arrive until Julia v1.9 or v1.10 though.

It would also be possible to solve this problem now (i.e. v1.8 or earlier) using Requires.jl, but I'm not keen to do that as an interim fix unless it is causing serious issues for you.   

Would you be happy to wait on julia v1.10 for this?   If so I will leave the issue open as a reminder to come back and fix it when new functionality arrives.

**Comment by goulart-paul** [comment]
It turns out to be very simple to implement support in Requires.jl, so I made a fix in #111.    We will consider making this part of v0.4.0 as an interim fix.

**Comment by goulart-paul** [comment]
Fixed in #111 / #114.
