### ISSUE TITLE
Hermitian PSD cone

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/Clarabel.jl#133]
Is there any plan to add support the the Hermitian PSD cone ? It would help for instance for the OPF tutorial, see e.g., https://github.com/jump-dev/JuMP.jl/pull/3432

**Comment by goulart-paul** [comment]
I think not, unless @migarstka has some plans to the contrary.

**Comment by blegat** [comment]
I indeed also have the same question for COSMO as well :innocent:

**Comment by goulart-paul** [comment]
@blegat : yikes, sorry.   Thought I was responding in the COSMO repo.

The answer is still no though I think.
