### ISSUE TITLE
Citing Clarabel.jl in an academic paper

### ISSUE THREAD

**Issue by mattgiamou** [oxfordcontrol/Clarabel.jl#163]
What paper(s) should I cite if I use Clarabel.jl in experiments for an academic paper? I've made good use of it and want to make sure I properly assign credit where it's due. Apologies if this is in plain sight, but I couldn't find it. Thanks!

**Comment by goulart-paul** [comment]
No apology necessary, as the paper was only released today.    Paper preprint now available [here](https://arxiv.org/abs/2405.12762).

I also put a .bib entry in the README of this repo and on our documentation pages.

**Comment by mattgiamou** [comment]
Amazing, looking forward to reading it!
