### ISSUE TITLE
Added to ConvexTests

### ISSUE THREAD

**Issue by ericphanson** [oxfordcontrol/Clarabel.jl#75]
Thanks for making this cool solver available! I've added it to [ConvexTests.jl](https://github.com/ericphanson/ConvexTests.jl), which uses test problems from Convex.jl and SumOfSquares.jl in order to test the reliability of Julia-accessible solvers. So these are somewhat weird problems that tend to test edge cases, rather than standard benchmarking problems. I started it when I couldn't find a single solver that could solve all of the problems from Convex.jl's tests (in order to run in CI). 

You can see the results for Clarabel here: https://ericphanson.github.io/ConvexTests.jl/dev/Clarabel/

If you would prefer ConvexTests to run the solver with different settings, you can make a PR to adjust them here: https://github.com/ericphanson/ConvexTests.jl/blob/9653106903f05143a0785e5560fd9d5a8f52690d/Clarabel/test.jl#L6-L11

If you are interested, it also possible to run Convex's tests as part of your own test suite to prevent regression on these problems. See e.g. https://jump.dev/Convex.jl/stable/problem_depot/#Problem-Depot.

**Comment by goulart-paul** [comment]
Thank you for this, it is very helpful.   We will have a look and clean up the edge cases.    

It seems that you do not test QP problems directly.   Is that because it is run through Convex.jl, which would reformulate QPs to SOCPs anyway?

**Comment by ericphanson** [comment]
> It seems that you do not test QP problems directly. Is that because it is run through Convex.jl, which would reformulate QPs to SOCPs anyway?

Yeah, the Convex problems are from here: https://github.com/jump-dev/Convex.jl/tree/master/src/problem_depot/problems. They were taken from Convex.jl's tests, built over a few years (mostly before my time helping maintain Convex). I guess we just never added QP problems, probably for the reason you say.

The SumOfSquares tests are here: https://github.com/jump-dev/SumOfSquares.jl/tree/master/test/Tests

**Comment by goulart-paul** [comment]
Thanks again.   We have made some stability improvements and added exp and pow cones in v0.3.0.   I have made a PR to ConvexTests.jl with this change.
