### ISSUE TITLE
License links don't work

### ISSUE THREAD

**Issue by DanielVandH** [oxfordcontrol/Clarabel.jl#77]
The license links in the README (and in other places it's referred to, probably - I think the only other place is at the bottom of https://oxfordcontrol.github.io/Clarabel.jl/stable/) do not work. Currently they lead to

https://github.com/oxfordcontrol/Clarabel.jl/blob/main/LICENSE.md

when it should be 

https://github.com/oxfordcontrol/Clarabel.jl/blob/main/LICENSE.

I was going to edit it but I wasn't sure if you'd want the link change, or the extension to be corrected to .md in the repository.

**Comment by goulart-paul** [comment]
Thanks.   I have renamed the file and corrected paths to it, some of which were also .../master/... instead of .../main/...
