### ISSUE TITLE
collect method for cones

### ISSUE THREAD

**Issue by PaulSoderlind** [oxfordcontrol/Clarabel.jl#86]
as discussed at https://discourse.julialang.org/t/ann-clarabel-jl-new-convex-optimization-solver/83915

To filter out the b[i]==Inf cases, I currently need to build the vector cones in a loop, so it has as many elements as length(b). Then, I can index into it with cones[.!isinf.(b)].

It would nice if I could create this vector by collect([NonnegativeConeT(2)]) or similarly to allow the indexing.

**Comment by PaulSoderlind** [comment]
> all linear inequalities

My typical use case has also linear equalities, which I have handled with `Clarabel.ZeroConeT(1)`. I guess I could reorder the restrictions to get the equalities first and then apply your idea. (Replacing an equality with two inequalities is not a good idea, or?)

**Comment by goulart-paul** [comment]
We have implemented a feature that will automatically eliminate constraints with very large bounds, which I think means that that the issue described here is no longer relevant.     This is now part of release v0.4.1. 

I will close, but feel free to reopen if I have misunderstood.
