### ISSUE TITLE
Issue for 1D problem

### ISSUE THREAD

**Issue by mathleur** [oxfordcontrol/Clarabel.jl#88]
The issue arises for the problem:

using Clarabel, LinearAlgebra, SparseArrays

settings = Clarabel.Settings(verbose = true)
settings.direct_solve_method=:cholmod
settings.tol_feas =10^-4
settings.tol_gap_abs=10^-4
settings.max_iter=1
solver   = Clarabel.Solver()

P = sparse(Matrix(I,1,1))
q = [0.]
nothing  #hide

A = sparse([1.;   
            ])

b = [0*ones(1)]

cones =
    [Clarabel.NonnegativeConeT(1)]    

nothing  #hide

Clarabel.setup!(solver, P, q, A, b, cones, settings)
result = Clarabel.solve!(solver)

The Stacktrace:

[1] Dict{Symbol, Union{}}()
       @ Base .\dict.jl:88
     [2] Dict
       @ .\dict.jl:101 [inlined]
     [3] dict_with_eltype
       @ .\abstractdict.jl:537 [inlined]
     [4] Dict(kv::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       @ Base .\dict.jl:129
     [5] setup!(s::Clarabel.Solver{Float64}, P::SparseMatrixCSC{Bool, Int64}, c::Vector{Float64}, A::SparseVector{Float64, Int64}, b::Vector{Vector{Float64}}, cone_types::Vector{Clarabel.NonnegativeConeT}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})

**Comment by goulart-paul** [comment]
The issue is that the `A` argument is a 1 element sparse vector, not a SparseMatrixCSC.   You could use 
```
A = sparse(I(1).*1.)
```
instead.   Does that work?

**Comment by mathleur** [comment]
I think it still doesn't work. 
I also tried A=sparse(Matrix(I,1,1).*1.) and sparse(I,1,1).*1. which give SparseMatrixCSC{Bool, Float64}, but this does not work either.

**Comment by goulart-paul** [comment]
The issue was that this line 

```
b = [0*ones(1)]
```

produces a `b` that is of type `Vector{Vector{Float64}}`.   It should instead be 

```
b = zeros(1)
```

The following works:

```julia 
settings = Clarabel.Settings(verbose = true)
solver = Clarabel.Solver()

P = A = sparse(I(1).*1.)
q = [0.]

A = A = sparse(I(1).*1.)
b = zeros(1)

cones = [Clarabel.NonnegativeConeT(1)]

Clarabel.setup!(solver, P, q, A, b, cones, settings)
result = Clarabel.solve!(solver)
```
